version: "3.8"

services:
  app1:
    container_name: phytmorph1
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    ports:
      - "6080:6080"
    restart: unless-stopped
  app2:
    container_name: mutant1
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    ports:
      - "6081:6080"
    restart: unless-stopped
  app3:
    container_name: benchmark1
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    ports:
      - "6082:6080"
    restart: unless-stopped
  app4:
    container_name: benchmark2
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    ports:
      - "6083:6080"
    restart: unless-stopped
